version: '3.8'
services:
  web:
    # build: <chemin_vers_dossier_contenant_dockerfile>
    build: .
    volumes:
      - ./src/hotel:/app/src/hotel
    ports:
    # - <HOST_PORT>:<CONTAINER_PORT>
      - 5001:5001
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: hotel
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: